# Generated by Django 5.2.11 on 2026-07-25 05:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Department Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "mst_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="District Name"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="MultiPolygon Geometry",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "mst_district",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GISCatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer_name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Layer Name"
                    ),
                ),
                (
                    "geometry_type",
                    models.CharField(
                        max_length=50,
                        verbose_name="Geometry Type (Point, Line, Polygon, Raster)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=100,
                        verbose_name="Category (Health, Water, Hazard, Landuse)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Is Published to GeoServer?"
                    ),
                ),
            ],
            options={
                "verbose_name": "GIS Catalog Entry",
                "verbose_name_plural": "GIS Catalog Entries",
                "db_table": "gis_catalog_entry",
            },
        ),
        migrations.CreateModel(
            name="GISProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_type", models.CharField(max_length=100, verbose_name="Job Type")),
                (
                    "status",
                    models.CharField(
                        default="PENDING", max_length=50, verbose_name="Status"
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parameters (JSONB)"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "GIS Processing Job",
                "verbose_name_plural": "GIS Processing Jobs",
                "db_table": "gis_processing_job",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Template Name"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PUSH", "Push Notification"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="EN", max_length=10, verbose_name="Locale (EN, HI)"
                    ),
                ),
                ("body_template", models.TextField(verbose_name="Body Template Text")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "ntf_template",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Role Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NATIONAL_ADMIN", "National Admin"),
                            ("STATE_ADMIN", "State Admin"),
                            ("DISTRICT_COLLECTOR", "District Collector / DM"),
                            ("ADM", "Additional District Magistrate (ADM)"),
                            ("DEPARTMENT_OFFICER", "Department Officer"),
                            (
                                "FIELD_ENGINEER_DEO",
                                "Field Engineer / Data Entry Operator",
                            ),
                            ("CITIZEN_REGISTERED", "Registered Citizen"),
                            ("CITIZEN_ANONYMOUS", "Anonymous Citizen"),
                        ],
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Role Code",
                    ),
                ),
                (
                    "scope_level",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National Scope (All States/Districts)"),
                            ("STATE", "State Scope (All Districts in State)"),
                            (
                                "DISTRICT",
                                "District Scope (Assigned District, All Depts)",
                            ),
                            (
                                "DEPARTMENT",
                                "Department Scope (Assigned District + Dept)",
                            ),
                            ("SELF", "Self Scope (Own Submissions)"),
                            ("ANONYMOUS", "Public Read-Only"),
                        ],
                        default="DISTRICT",
                        max_length=20,
                        verbose_name="Scope Level",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Role Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "RBAC Role",
                "verbose_name_plural": "RBAC Roles",
                "db_table": "rbac_role",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="State Name"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "mst_state",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Workflow Type (PROPOSAL, GRIEVANCE, ALERT)",
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        default="DRAFT", max_length=100, verbose_name="Current State"
                    ),
                ),
                (
                    "sla_due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA Due At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Workflow Instance",
                "verbose_name_plural": "Workflow Instances",
                "db_table": "txn_workflow_instance",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Official Designation"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="myapp.department",
                        verbose_name="Assigned Department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="myapp.district",
                        verbose_name="Assigned District",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="myapp.role",
                        verbose_name="Assigned Role",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="myapp.state",
                        verbose_name="Assigned State",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "mst_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Target Entity Type"
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(db_index=True, verbose_name="Target Entity UUID"),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=50,
                        verbose_name="Action (CREATE, UPDATE, DELETE, APPROVE)",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Before State (JSONB)"
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="After State (JSONB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event Log",
                "verbose_name_plural": "Audit Event Logs",
                "db_table": "aud_event_log",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="DataCustodian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.CharField(max_length=200, verbose_name="Contact Details"),
                ),
                (
                    "designation",
                    models.CharField(max_length=150, verbose_name="Designation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custodians",
                        to="myapp.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Custodian",
                "verbose_name_plural": "Data Custodians",
                "db_table": "mst_data_custodian",
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Category Name"),
                ),
                (
                    "field_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema specifying custom fields for this category",
                        verbose_name="Field Schema (JSONB)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="myapp.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
                "db_table": "mst_asset_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Facility Name"),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Dynamic Attributes (JSONB)",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Geometry Location",
                    ),
                ),
                (
                    "hazard_safe",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is Hazard Safe?"
                    ),
                ),
                (
                    "hazard_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Hazard Exposure Flags (JSONB)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facilities",
                        to="myapp.assetcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="myapp.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="myapp.district",
                        verbose_name="District",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility / Spatial Asset",
                "verbose_name_plural": "Facilities & Spatial Assets",
                "db_table": "ast_facility",
            },
        ),
        migrations.CreateModel(
            name="FacilityHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Valid From"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid To"
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        default=dict, verbose_name="Facility State Snapshot (JSONB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_records",
                        to="myapp.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility History Record",
                "verbose_name_plural": "Facility History Records",
                "db_table": "ast_facility_history",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="GapScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Gap Score Metric"
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Detailed Metrics (JSONB)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_scores",
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_scores",
                        to="myapp.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Gap Score",
                "verbose_name_plural": "Analytics Gap Scores",
                "db_table": "anl_gap_score",
            },
        ),
        migrations.CreateModel(
            name="GISDataProvenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        max_length=255,
                        verbose_name="Data Source (NRSC, Bhuvan, ESA, USGS, Survey of India)",
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Data License"
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata (JSONB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "catalog_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance",
                        to="myapp.giscatalogentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "GIS Data Provenance",
                "verbose_name_plural": "GIS Data Provenances",
                "db_table": "gis_data_provenance",
            },
        ),
        migrations.CreateModel(
            name="GISDatasetVersionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_no", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "catalog_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="myapp.giscatalogentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "GIS Dataset Version History",
                "verbose_name_plural": "GIS Dataset Version Histories",
                "db_table": "gis_dataset_version_history",
            },
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        max_length=50, verbose_name="Source Type (CSV, SHP, GeoJSON)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="PENDING", max_length=50, verbose_name="Batch Status"
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("processed_records", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Batch",
                "verbose_name_plural": "Ingestion Batches",
                "db_table": "ast_ingestion_batch",
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="ingestion_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facilities",
                to="myapp.ingestionbatch",
            ),
        ),
        migrations.CreateModel(
            name="NotificationDispatchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="DISPATCHED", max_length=50)),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Dispatch Log",
                "verbose_name_plural": "Notification Dispatch Logs",
                "db_table": "ntf_dispatch_log",
                "ordering": ["-dispatched_at"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        max_length=100,
                        verbose_name="Resource (e.g. facility, proposal)",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=50,
                        verbose_name="Action (e.g. create, read, approve)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Permission Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "RBAC Permission",
                "verbose_name_plural": "RBAC Permissions",
                "db_table": "rbac_permission",
                "unique_together": {("resource", "action")},
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Proposal Title"),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Estimated Cost (INR)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="myapp.district",
                    ),
                ),
                (
                    "gap_score_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="myapp.gapscore",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="myapp.workflowinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Proposal",
                "verbose_name_plural": "Department Proposals",
                "db_table": "txn_proposal",
            },
        ),
        migrations.CreateModel(
            name="BudgetApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Approved Amount (INR)",
                    ),
                ),
                (
                    "approved_via",
                    models.CharField(
                        max_length=150, verbose_name="Sanction Order Number / Path"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_approvals",
                        to="myapp.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Approval",
                "verbose_name_plural": "Budget Approvals",
                "db_table": "txn_budget_approval",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_class",
                    models.CharField(
                        max_length=150,
                        verbose_name="Decision Class (e.g. Recommend PHC, Solar Site)",
                    ),
                ),
                (
                    "spatial_evidence",
                    models.JSONField(
                        default=dict, verbose_name="Linked Spatial Evidence (JSONB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "gap_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="myapp.gapscore",
                    ),
                ),
            ],
            options={
                "verbose_name": "SDSS Recommendation",
                "verbose_name_plural": "SDSS Recommendations",
                "db_table": "anl_recommendation",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_roles",
                        to="myapp.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="myapp.role",
                    ),
                ),
            ],
            options={
                "db_table": "rbac_role_permission",
            },
        ),
        migrations.AddField(
            model_name="district",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="myapp.state",
                verbose_name="State",
            ),
        ),
        migrations.CreateModel(
            name="SubDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="SubDivision Name"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="MultiPolygon Geometry",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdivisions",
                        to="myapp.district",
                        verbose_name="District",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Division",
                "verbose_name_plural": "Sub-Divisions",
                "db_table": "mst_subdivision",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Block Name")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="MultiPolygon Geometry",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "subdivision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="myapp.subdivision",
                        verbose_name="Sub-Division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "db_table": "mst_block",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserDistrictScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scopes",
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scopes",
                        to="myapp.district",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rbac_user_district_scope",
            },
        ),
        migrations.CreateModel(
            name="VillageWard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Village/Ward Name"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="MultiPolygon Geometry",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages_wards",
                        to="myapp.block",
                        verbose_name="Block",
                    ),
                ),
            ],
            options={
                "verbose_name": "Village/Ward",
                "verbose_name_plural": "Villages & Wards",
                "db_table": "mst_village_ward",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CitizenGrievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tracking Number"
                    ),
                ),
                (
                    "citizen_name",
                    models.CharField(max_length=150, verbose_name="Citizen Name"),
                ),
                (
                    "citizen_phone",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("description", models.TextField(verbose_name="Grievance Description")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Point Geometry"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "citizen_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grievances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grievances",
                        to="myapp.facility",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grievances",
                        to="myapp.workflowinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Citizen Grievance",
                "verbose_name_plural": "Citizen Grievances",
                "db_table": "txn_citizen_grievance",
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_state",
                    models.CharField(max_length=100, verbose_name="From State"),
                ),
                ("to_state", models.CharField(max_length=100, verbose_name="To State")),
                (
                    "remarks",
                    models.TextField(blank=True, verbose_name="Transition Remarks"),
                ),
                ("transitioned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="myapp.workflowinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Transition",
                "verbose_name_plural": "Workflow Transitions",
                "db_table": "txn_workflow_transition",
                "ordering": ["-transitioned_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Owner Entity Type (FACILITY, PROPOSAL, GRIEVANCE)",
                    ),
                ),
                ("owner_id", models.UUIDField(verbose_name="Owner Record UUID")),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="File Attachment"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="File Name"),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="File Version"),
                ),
                (
                    "signature_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Digital Signature Reference",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document File",
                "verbose_name_plural": "Document Files",
                "db_table": "doc_file",
                "indexes": [
                    models.Index(
                        fields=["owner_type", "owner_id"],
                        name="doc_file_owner_t_9ae53c_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["district", "department"], name="ast_facilit_distric_a1ec8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facility",
            index=models.Index(
                fields=["hazard_safe"], name="ast_facilit_hazard__e70c51_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("state", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="subdivision",
            unique_together={("district", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("subdivision", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="userdistrictscope",
            unique_together={("user", "district", "department")},
        ),
    ]
