# Generated by Django 5.2.11 on 2026-07-27 05:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_department_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giscatalogentry",
            options={
                "ordering": ["category", "layer_name"],
                "verbose_name": "GIS Catalog Entry",
                "verbose_name_plural": "GIS Catalog Entries",
            },
        ),
        migrations.AddField(
            model_name="giscatalogentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="giscatalogentry",
            name="feature_count",
            field=models.IntegerField(default=0, verbose_name="Feature Count"),
        ),
        migrations.AddField(
            model_name="giscatalogentry",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="giscatalogentry",
            name="category",
            field=models.CharField(
                max_length=100,
                verbose_name="Category (Health, Water, Hazard, Landuse, Admin, Infra)",
            ),
        ),
        migrations.CreateModel(
            name="GISLayerFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Feature Identifier",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Feature Name",
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Attributes (JSONB)"
                    ),
                ),
                (
                    "geom_geojson",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="GeoJSON Geometry (WGS84 EPSG:4326)",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Geometry Location",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "catalog_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="myapp.giscatalogentry",
                        verbose_name="GIS Layer Catalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "GIS Layer Feature",
                "verbose_name_plural": "GIS Layer Features",
                "db_table": "gis_layer_feature",
                "indexes": [
                    models.Index(
                        fields=["catalog_entry"], name="gis_layer_f_catalog_522c45_idx"
                    ),
                    models.Index(fields=["name"], name="gis_layer_f_name_9fc84b_idx"),
                ],
            },
        ),
    ]
