# Generated by Django 5.2.11 on 2026-07-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_giscatalogentry_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DataCustodian",
            new_name="DepartmentOfficer",
        ),
    ]
