# Generated by Django 5.2.11 on 2026-07-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_datacustodian_departmentofficer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentofficer",
            options={
                "verbose_name": "Department Officer",
                "verbose_name_plural": "Department Officers",
            },
        ),
        migrations.AddField(
            model_name="departmentofficer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AddField(
            model_name="departmentofficer",
            name="name",
            field=models.CharField(
                default="", max_length=150, verbose_name="Officer Name"
            ),
        ),
        migrations.AddField(
            model_name="departmentofficer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="officer_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Account",
            ),
        ),
        migrations.AlterField(
            model_name="departmentofficer",
            name="contact",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Contact Details / Phone",
            ),
        ),
        migrations.AlterField(
            model_name="departmentofficer",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="officers",
                to="myapp.department",
                verbose_name="Department",
            ),
        ),
    ]
