# Generated by Django 5.2.11 on 2026-08-03 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_assetcategory_catalog_entry_facility_catalog_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='catalog_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='myapp.giscatalogentry', verbose_name='GIS Catalog Layer'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='catalog_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='myapp.giscatalogentry', verbose_name='GIS Catalog Layer'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='gis_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='myapp.gislayerfeature', verbose_name='Source GIS Feature'),
        ),
    ]
