# Generated by Django 5.2.11 on 2026-08-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_assetcategory_catalog_entry_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CitizenGrievance',
            new_name='Citizencomplain',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='ingestion_batch',
        ),
        migrations.DeleteModel(
            name='IngestionBatch',
        ),
    ]
