# Generated by Django 5.2.11 on 2026-08-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_citizengrievance_citizencomplain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizencomplain',
            options={'verbose_name': 'Citizen complain', 'verbose_name_plural': 'Citizen complains'},
        ),
        migrations.AlterModelTable(
            name='citizencomplain',
            table='txn_citizen_complain',
        ),
    ]
