# Generated by Django 5.2.11 on 2026-08-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_citizencomplain_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citizencomplain',
            new_name='Citizengrievance',
        ),
        migrations.AlterModelOptions(
            name='citizengrievance',
            options={'verbose_name': 'Citizen grievance', 'verbose_name_plural': 'Citizen grievances'},
        ),
        migrations.AlterModelTable(
            name='citizengrievance',
            table='txn_citizen_grievance',
        ),
    ]
