# Generated by Django 5.2.11 on 2026-08-04 12:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_citizencomplain_citizengrievance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Health', 'health'), ('Education', 'education'), ('Transport', 'transport'), ('Hydrology', 'hydrology'), ('Environment', 'environment'), ('Hazards', 'hazards'), ('Civic', 'civic'), ('Other', 'other')], max_length=150, unique=True, verbose_name='Department Name'),
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category Name')),
                ('default_priority', models.CharField(choices=[('LOW', 'Low (72h SLA)'), ('MEDIUM', 'Medium (48h SLA)'), ('HIGH', 'High (24h SLA)'), ('CRITICAL', 'Critical (6h SLA)')], default='MEDIUM', max_length=20, verbose_name='Default Priority')),
                ('default_sla_hours', models.IntegerField(default=24, verbose_name='Default SLA (Hours)')),
                ('icon', models.CharField(default='fa-circle-exclamation', max_length=50, verbose_name='FontAwesome Icon')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_categories', to='myapp.department', verbose_name='Auto-Route Department')),
            ],
            options={
                'verbose_name': 'Complaint Category',
                'verbose_name_plural': 'Complaint Categories',
                'db_table': 'cmp_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Tracking Number')),
                ('title', models.CharField(max_length=255, verbose_name='Complaint Title')),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('citizen_name', models.CharField(max_length=150, verbose_name='Citizen Name')),
                ('citizen_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('citizen_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('is_identity_masked', models.BooleanField(default=False, verbose_name='Mask Identity on Public Portals')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('INSPECTION_STARTED', 'Inspection Started'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('RESOLVED', 'Resolved'), ('CITIZEN_VERIFICATION', 'Citizen Verification'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('TRANSFERRED', 'Transferred'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=30, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low (72h SLA)'), ('MEDIUM', 'Medium (48h SLA)'), ('HIGH', 'High (24h SLA)'), ('CRITICAL', 'Critical (6h SLA)')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('sla_target_hours', models.IntegerField(default=24, verbose_name='SLA Target (Hours)')),
                ('sla_deadline', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='SLA Deadline')),
                ('is_sla_breached', models.BooleanField(db_index=True, default=False, verbose_name='SLA Breached Flag')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point Geometry')),
                ('nearest_facility_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nearest Facility Name')),
                ('nearest_facility_distance_m', models.FloatField(blank=True, null=True, verbose_name='Distance to Nearest Facility (Meters)')),
                ('resolution_summary', models.TextField(blank=True, null=True, verbose_name='Resolution Summary')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('transfer_reason', models.TextField(blank=True, null=True, verbose_name='Transfer Reason')),
                ('escalation_reason', models.TextField(blank=True, null=True, verbose_name='Escalation Reason')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Citizen Feedback Rating (1-5)')),
                ('feedback_comment', models.TextField(blank=True, null=True, verbose_name='Citizen Feedback Comment')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Field Inspector')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Department Officer / Engineer')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='myapp.block')),
                ('citizen_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='myapp.department', verbose_name='Responsible Department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='myapp.district')),
                ('nearest_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearest_complaints', to='myapp.facility')),
                ('nearest_gis_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearest_complaints', to='myapp.gislayerfeature')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='myapp.subdivision')),
                ('village_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='myapp.villageward')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='myapp.complaintcategory')),
            ],
            options={
                'verbose_name': 'Complaint / Grievance',
                'verbose_name_plural': 'Complaints & Grievances',
                'db_table': 'cmp_complaint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/evidence/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='IMAGE', max_length=50)),
                ('stage', models.CharField(choices=[('SUBMISSION', 'Citizen Submission'), ('INSPECTION', 'Field Inspection'), ('RESOLUTION', 'Resolution Verification')], default='SUBMISSION', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='EXIF Geotag Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='EXIF Geotag Longitude')),
                ('is_geotag_verified', models.BooleanField(default=True, verbose_name='Geotag Matches Pin Tolerance')),
                ('distance_from_pin_m', models.FloatField(blank=True, null=True, verbose_name='Distance from Pin (Meters)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='myapp.complaint')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Evidence',
                'verbose_name_plural': 'Complaint Evidences',
                'db_table': 'cmp_evidence',
            },
        ),
        migrations.CreateModel(
            name='ComplaintTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action Taken')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(blank=True, max_length=30, null=True)),
                ('performer_role', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='myapp.complaint')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Timeline Event',
                'verbose_name_plural': 'Complaint Timeline Events',
                'db_table': 'cmp_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'department'], name='cmp_complai_status_a0e0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_officer', 'status'], name='cmp_complai_assigne_5572c3_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['citizen_user'], name='cmp_complai_citizen_c57143_idx'),
        ),
    ]
