# Generated by Django 5.2.11 on 2026-08-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_department_name_complaintcategory_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='citizen_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Citizen Name'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='citizen_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='myapp.department', verbose_name='Responsible Department'),
        ),
    ]
