# Generated by Django 5.2.11 on 2026-08-08 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_complaint_citizen_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Department Proposal', 'verbose_name_plural': 'Department Proposals'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='Attached DPR Files & Drawings'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='block',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Block (e.g. Silao)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.CharField(default='Infrastructure', max_length=150, verbose_name='Proposal Category'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='civil_works',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Civil Works (INR)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='clearances',
            field=models.JSONField(blank=True, default=dict, verbose_name='Departmental Clearances (JSONB)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='contingency_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Contingency Cost (INR)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='delegated_power_note',
            field=models.CharField(default='Within DM delegated power', max_length=255, verbose_name='Delegated Power Note'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='electrical_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Electrical Cost (INR)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='engineering_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Engineering Notes & Dependencies'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='equipment_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Equipment Cost (INR)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='estimated_timeline',
            field=models.CharField(default='90 days', max_length=100, verbose_name='Estimated Timeline'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gap_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Gap Score Metric'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gis_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GIS Reference (Selected site)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inspection Date'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='inspection_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Inspection Notes / Existing Infrastructure'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Site Latitude'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='linked_complaint_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Linked Complaint IDs'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Site Longitude'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Maintenance Cost (INR)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='population_impact',
            field=models.IntegerField(default=0, verbose_name='Population Impact'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority Level'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='problem_statement',
            field=models.TextField(blank=True, null=True, verbose_name='Problem Statement and Reason'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Proposal ID (e.g. PRP-2026-00104)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='review_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Reviewer Notes / Observations'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='stage',
            field=models.CharField(choices=[('1_NEED_IDENTIFICATION', '1. Need Identification'), ('2_SURVEY_INSPECTION', '2. Survey & Inspection'), ('3_TECHNICAL_DPR', '3. Technical DPR'), ('4_FINANCIAL_ESTIMATION', '4. Financial Estimation'), ('5_CLEARANCES', '5. Clearances'), ('6_ATTACHMENTS', '6. Attachments'), ('7_REVIEW_SUBMIT', '7. Review & Submit')], default='1_NEED_IDENTIFICATION', max_length=50, verbose_name='Current DPR Stage'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DEVELOPMENT_NEEDS', 'Development Needs'), ('DRAFT_DPR', 'Draft DPR'), ('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('SANCTIONED', 'Sanctioned'), ('REJECTED', 'Rejected'), ('IN_EXECUTION', 'In Execution')], default='DRAFT_DPR', max_length=50, verbose_name='Proposal Status'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='survey_team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Survey Team (Officers/Engineers)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='technical_scope',
            field=models.TextField(blank=True, null=True, verbose_name='Technical Scope & Execution Method'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Village'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ward',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='myapp.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='myapp.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Grand Total Estimated Cost (INR)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(blank=True, choices=[('CITIZEN', 'Citizen'), ('DISTRICT_COLLECTOR', 'District Collector'), ('DISTRICT_MAGISTRATE', 'District Magistrate (DM)'), ('ADM', 'Additional District Magistrate (ADM)'), ('DEPARTMENT_HEAD', 'Department Head'), ('DEPARTMENT_OFFICER', 'Department Officer'), ('EXECUTIVE_ENGINEER', 'Executive / Assistant Engineer'), ('FIELD_INSPECTOR', 'Field Inspector / Junior Engineer'), ('FIELD_SUPERVISOR', 'Field Supervisor'), ('STATE_ADMIN', 'State Admin')], max_length=50, null=True, unique=True, verbose_name='Role Code'),
        ),
    ]
