# Generated by Django 5.2.11 on 2026-08-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_proposal_options_proposal_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='linked_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='myapp.complaint', verbose_name='Linked Primary Complaint'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='myapp.state', verbose_name='State'),
        ),
        migrations.DeleteModel(
            name='Citizengrievance',
        ),
    ]
