# Generated by Django 5.2.11 on 2026-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_proposal_linked_complaint_proposal_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='clearances_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Clearances & NOCs Notes'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='funding_source',
            field=models.CharField(default='District', max_length=150, verbose_name='Funding Source'),
        ),
    ]
