# Generated by Django 5.2.11 on 2026-08-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_proposal_clearances_notes_proposal_funding_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='funding_source',
            field=models.CharField(choices=[('District', 'District'), ('State', 'State'), ('Central', 'Central'), ('CSR', 'CSR'), ('World Bank', 'World Bank'), ('ADB', 'ADB'), ('Other', 'Other')], default='District', max_length=150, verbose_name='Funding Source'),
        ),
    ]
