# Generated by Django 5.2.11 on 2026-08-10 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_proposal_funding_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True, verbose_name='Project ID (e.g. PRJ-2026-00103)')),
                ('title', models.CharField(max_length=255, verbose_name='Project Name')),
                ('block', models.CharField(blank=True, max_length=150, verbose_name='Block')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Ward')),
                ('contractor_name', models.CharField(blank=True, max_length=200, verbose_name='Contractor Name')),
                ('sanction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Sanctioned Budget (INR)')),
                ('expenditure_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Budget Utilized (INR)')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Progress %')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_execution', 'In Execution'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('handed_over', 'Handed Over')], default='in_execution', max_length=50, verbose_name='Execution Status')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Risk Level')),
                ('inspection_due', models.BooleanField(default=False, verbose_name='Inspection Due')),
                ('inspection_due_date', models.DateField(blank=True, null=True, verbose_name='Inspection Due Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('target_completion_date', models.DateField(blank=True, null=True, verbose_name='Target Completion Date')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='myapp.department', verbose_name='Department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='myapp.district', verbose_name='District')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_projects', to='myapp.proposal', verbose_name='Linked DPR Proposal')),
            ],
            options={
                'verbose_name': 'Project Execution',
                'verbose_name_plural': 'Project Executions',
                'db_table': 'prj_project_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True, verbose_name='Bill Number')),
                ('bill_type', models.CharField(default='RA_BILL', max_length=50, verbose_name='Bill Type (RA / Advance / Final)')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Claimed Amount (INR)')),
                ('verified_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Verified Amount (INR)')),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Deductions (TDS/Security) (INR)')),
                ('net_payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Net Payable Amount (INR)')),
                ('submission_date', models.DateField(default=django.utils.timezone.now, verbose_name='Submission Date')),
                ('payment_status', models.CharField(default='submitted', max_length=50, verbose_name='Payment Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='PFMS / Treasury Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='myapp.projectexecution', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Bill & Payment',
                'verbose_name_plural': 'Project Bills & Payments',
                'db_table': 'prj_project_bill',
                'ordering': ['-submission_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_number', models.CharField(max_length=50, unique=True, verbose_name='MB Entry Number')),
                ('item_description', models.TextField(verbose_name='Quantity / Work Item Description')),
                ('unit', models.CharField(default='Cum', max_length=50, verbose_name='Unit of Measurement')),
                ('quantity_measured', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Quantity Measured')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rate per Unit (INR)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Valuation (INR)')),
                ('measurement_date', models.DateField(default=django.utils.timezone.now, verbose_name='Measurement Date')),
                ('measured_by', models.CharField(blank=True, max_length=150, verbose_name='Measured By (Junior Engineer)')),
                ('verified_by', models.CharField(blank=True, max_length=150, verbose_name='Verified By (Executive Engineer)')),
                ('status', models.CharField(default='submitted', max_length=50, verbose_name='Verification Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_entries', to='myapp.projectexecution', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Measurement Book Entry',
                'verbose_name_plural': 'Measurement Book Entries',
                'db_table': 'prj_measurement_book',
                'ordering': ['-measurement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(default='schedule_delay', max_length=100, verbose_name='Risk Category')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity')),
                ('risk_signal', models.TextField(verbose_name='Risk Signal / Issue Statement')),
                ('recommendation', models.TextField(verbose_name='Recommendation / Mitigation Plan')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='Risk Status')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reported At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_signals', to='myapp.projectexecution', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Execution Risk Signal',
                'verbose_name_plural': 'Execution Risk Signals',
                'db_table': 'prj_execution_risk',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.now, verbose_name='Log Date')),
                ('work_description', models.TextField(verbose_name='Engineer Notes / Work Executed')),
                ('labour_count', models.IntegerField(default=0, verbose_name='Labour Count')),
                ('materials_used', models.TextField(blank=True, verbose_name='Materials Used')),
                ('weather_condition', models.CharField(default='Sunny', max_length=100, verbose_name='Weather Condition')),
                ('progress_logged', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Progress % Logged')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logs', to=settings.AUTH_USER_MODEL, verbose_name='Logged By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_diaries', to='myapp.projectexecution', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Site Diary Log',
                'verbose_name_plural': 'Site Diary Logs',
                'db_table': 'prj_site_diary',
                'ordering': ['-log_date', '-created_at'],
            },
        ),
    ]
