# Generated by Django 5.2.11 on 2026-08-10 07:41

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_projectexecution_projectbill_measurementbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexecution',
            name='proposed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Proposed Budget (INR)'),
        ),
        migrations.AddField(
            model_name='projectexecution',
            name='sanction_order_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sanction Order No'),
        ),
        migrations.AddField(
            model_name='projectexecution',
            name='sanctioned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sanctioned At'),
        ),
        migrations.AlterField(
            model_name='measurementbook',
            name='measurement_date',
            field=models.DateField(default=myapp.models.get_today_date, verbose_name='Measurement Date'),
        ),
        migrations.AlterField(
            model_name='projectbill',
            name='submission_date',
            field=models.DateField(default=myapp.models.get_today_date, verbose_name='Submission Date'),
        ),
        migrations.AlterField(
            model_name='sitediary',
            name='log_date',
            field=models.DateField(default=myapp.models.get_today_date, verbose_name='Log Date'),
        ),
    ]
