# Generated by Django 5.2.11 on 2026-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_projectexecution_proposed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementbook',
            name='estimated_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Estimated Quantity'),
        ),
        migrations.AlterField(
            model_name='measurementbook',
            name='quantity_measured',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Quantity Measured / Executed'),
        ),
    ]
