# Generated by Django 5.2.11 on 2026-08-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_measurementbook_estimated_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbill',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks / Observations'),
        ),
    ]
