# Generated by Django 5.2.11 on 2026-08-10 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_projectbill_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Report Code (e.g. REP-001)')),
                ('title', models.CharField(max_length=255, verbose_name='Report Title')),
                ('category', models.CharField(choices=[('SLA Audit', 'SLA Audit'), ('Asset Audit', 'Asset Audit'), ('Grievance Log', 'Grievance Log'), ('Workflow Audit', 'Workflow Audit')], default='SLA Audit', max_length=50, verbose_name='Category')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Report File')),
                ('file_size_str', models.CharField(default='2.4 MB', max_length=50, verbose_name='File Size (e.g. 2.4 MB)')),
                ('download_format', models.CharField(default='PDF', max_length=20, verbose_name='Format (PDF/CSV)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Generated Date')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='myapp.department', verbose_name='Department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='myapp.district', verbose_name='District')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'rpt_report',
                'ordering': ['code', '-generated_at'],
            },
        ),
    ]
