# Generated by Django 5.2.11 on 2026-08-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='myapp.role', verbose_name='RBAC Role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('dept_head', 'Department Head'), ('dept_officer', 'Department Officer'), ('engineer', 'Engineer'), ('field_inspector', 'Field Inspector')], default='dept_officer', max_length=50),
        ),
    ]
