# Generated by Django 5.2.11 on 2026-08-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_employee_role_fk_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role_fk',
        ),
        migrations.RunSQL("ALTER TABLE emp_employee ALTER COLUMN role DROP NOT NULL; UPDATE emp_employee SET role = NULL;"),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='myapp.role', verbose_name='Assigned Role'),
        ),
    ]
