# Generated by Django 5.2.11 on 2026-08-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_employee_options_remove_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='myapp.state'),
        ),
    ]
