# Generated by Django 5.2.11 on 2026-08-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_employee_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        default="2026-27",
                        max_length=20,
                        unique=True,
                        verbose_name="Financial Year (e.g. 2026-27)",
                    ),
                ),
                (
                    "total_state_budget_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=4800.0,
                        max_digits=14,
                        verbose_name="Total State Budget (₹ Cr)",
                    ),
                ),
                (
                    "department_allocation_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=4600.0,
                        max_digits=14,
                        verbose_name="Department Allocation (₹ Cr)",
                    ),
                ),
                (
                    "district_allocation_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=899.0,
                        max_digits=14,
                        verbose_name="District Allocation (₹ Cr)",
                    ),
                ),
                (
                    "total_sanctioned_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        max_digits=14,
                        verbose_name="Total Sanctioned (₹ Cr)",
                    ),
                ),
                (
                    "total_released_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=3900.0,
                        max_digits=14,
                        verbose_name="Total Released (₹ Cr)",
                    ),
                ),
                (
                    "total_committed_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=3200.0,
                        max_digits=14,
                        verbose_name="Total Committed (₹ Cr)",
                    ),
                ),
                (
                    "total_utilized_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=2850.0,
                        max_digits=14,
                        verbose_name="Total Utilized (₹ Cr)",
                    ),
                ),
                (
                    "available_balance_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=4596.0,
                        max_digits=14,
                        verbose_name="Available Balance (₹ Cr)",
                    ),
                ),
                (
                    "unreleased_balance_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        max_digits=14,
                        verbose_name="Unreleased Balance (₹ Cr)",
                    ),
                ),
                (
                    "active_projects_count",
                    models.IntegerField(
                        default=10, verbose_name="Active Projects Count"
                    ),
                ),
                (
                    "at_risk_projects_count",
                    models.IntegerField(
                        default=4, verbose_name="At Risk Projects Count"
                    ),
                ),
                (
                    "pending_approvals_count",
                    models.IntegerField(
                        default=4, verbose_name="Pending Approvals Count"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "State Master Budget",
                "verbose_name_plural": "State Master Budgets",
                "db_table": "fin_state_budget",
            },
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CITIZEN", "Citizen"),
                    ("DISTRICT_COLLECTOR", "District Collector"),
                    ("DISTRICT_MAGISTRATE", "District Magistrate (DM)"),
                    ("ADM", "Additional District Magistrate (ADM)"),
                    ("DEPARTMENT_HEAD", "Department Head"),
                    ("DEPARTMENT_OFFICER", "Department Officer"),
                    ("EXECUTIVE_ENGINEER", "Executive / Assistant Engineer"),
                    ("FIELD_INSPECTOR", "Field Inspector / Junior Engineer"),
                    ("FIELD_SUPERVISOR", "Field Supervisor"),
                    ("STATE_SUPER_ADMIN", "State Super Admin"),
                    ("STATE_ADMIN", "State Admin"),
                    ("STATE_FINANCE_ADMIN", "State Finance Admin"),
                    ("STATE_DEPARTMENT_ADMIN", "State Department Admin"),
                    ("STATE_MONITORING_OFFICER", "State Monitoring Officer"),
                    ("STATE_GIS_ADMIN", "State GIS Admin"),
                    ("SYSTEM_ADMINISTRATOR", "System Administrator"),
                ],
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Role Code",
            ),
        ),
        migrations.CreateModel(
            name="DistrictAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year", models.CharField(default="2026-27", max_length=20)),
                (
                    "allocation_amount_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Allocation Amount (₹ Cr)",
                    ),
                ),
                (
                    "sanctioned_amount_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Sanctioned Amount (₹ Cr)",
                    ),
                ),
                (
                    "utilized_amount_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Utilized Amount (₹ Cr)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="district_allocations",
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_allocations",
                        to="myapp.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "District Budget Allocation",
                "verbose_name_plural": "District Budget Allocations",
                "db_table": "fin_district_allocation",
            },
        ),
        migrations.CreateModel(
            name="SchemeMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Scheme Code"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Scheme Name")),
                (
                    "category",
                    models.CharField(
                        default="State Sponsored",
                        max_length=100,
                        verbose_name="Scheme Category",
                    ),
                ),
                (
                    "total_allocation_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Total Allocation (₹ Cr)",
                    ),
                ),
                (
                    "sanctioned_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Sanctioned Amount (₹ Cr)",
                    ),
                ),
                (
                    "released_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Released Amount (₹ Cr)",
                    ),
                ),
                (
                    "utilized_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Utilized Amount (₹ Cr)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="myapp.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Master",
                "verbose_name_plural": "Scheme Master Records",
                "db_table": "fin_scheme_master",
            },
        ),
        migrations.CreateModel(
            name="FinancialLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Transaction Ref ID"
                    ),
                ),
                ("financial_year", models.CharField(default="2026-27", max_length=20)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("PROVISION", "Budget Provision"),
                            ("AUTHORIZATION", "Authorization"),
                            ("ALLOCATION", "Department Allocation"),
                            ("SANCTION", "Authority Sanction"),
                            ("RELEASE", "Fund Release"),
                            ("COMMITMENT", "Financial Commitment"),
                            ("UTILIZATION", "Expenditure Utilization"),
                            ("RE_APPROPRIATION", "Re-appropriation Transfer"),
                        ],
                        default="ALLOCATION",
                        max_length=50,
                    ),
                ),
                (
                    "amount_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Amount (₹ Cr)",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, verbose_name="Transaction Remarks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.district",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.schememaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Ledger Entry",
                "verbose_name_plural": "Financial Ledger Entries",
                "db_table": "fin_ledger_entry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year", models.CharField(default="2026-27", max_length=20)),
                (
                    "authorized_budget_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Authorized Budget (₹ Cr)",
                    ),
                ),
                (
                    "sanctioned_budget_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Sanctioned Budget (₹ Cr)",
                    ),
                ),
                (
                    "released_budget_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Released Budget (₹ Cr)",
                    ),
                ),
                (
                    "committed_budget_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Committed Budget (₹ Cr)",
                    ),
                ),
                (
                    "utilized_budget_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Utilized Budget (₹ Cr)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_budgets",
                        to="myapp.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Budget",
                "verbose_name_plural": "Department Budgets",
                "db_table": "fin_department_budget",
                "unique_together": {("department", "financial_year")},
            },
        ),
    ]
