# Generated by Django 5.2.11 on 2026-08-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0028_alter_statebudget_financial_year_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DEVELOPMENT_NEEDS", "Development Needs"),
                    ("DRAFT_DPR", "Draft DPR"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("UNDER_NEGOTIATION", "Under Negotiation"),
                    ("APPROVED", "Approved"),
                    ("SANCTIONED", "Sanctioned"),
                    ("REJECTED", "Rejected"),
                    ("IN_EXECUTION", "In Execution"),
                ],
                default="DRAFT_DPR",
                max_length=50,
                verbose_name="Proposal Status",
            ),
        ),
        migrations.CreateModel(
            name="ProposalNegotiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("REQUEST_NEGOTIATION", "Request Negotiation"),
                            ("COUNTER_OFFER", "Counter Offer"),
                            ("ACCEPT", "Accept"),
                            ("REJECT", "Reject"),
                            ("WITHDRAW", "Withdraw"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "proposed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Proposed Amount",
                    ),
                ),
                (
                    "proposed_timeline_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Proposed Timeline (Days)"
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        blank=True, null=True, verbose_name="Proposed Scope"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="Remarks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations",
                        to="myapp.proposal",
                        verbose_name="Proposal",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal_negotiations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proposed By",
                    ),
                ),
            ],
            options={
                "db_table": "txn_proposal_negotiation",
                "ordering": ["created_at"],
            },
        ),
    ]
