# Generated by Django 5.2.11 on 2026-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_alter_proposal_status_proposalnegotiation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposalnegotiation",
            old_name="scope",
            new_name="proposed_scope",
        ),
        migrations.AddField(
            model_name="proposal",
            name="agreed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Agreed Amount (INR)",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="agreed_scope",
            field=models.TextField(blank=True, null=True, verbose_name="Agreed Scope"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="agreed_timeline_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Agreed Timeline (Days)"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="approval_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT", "Direct Approval"),
                    ("NEGOTIATED", "Negotiated Approval"),
                ],
                max_length=20,
                null=True,
                verbose_name="Approval Mode",
            ),
        ),
        migrations.AddField(
            model_name="proposalnegotiation",
            name="negotiation_round",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Negotiation Round Number"
            ),
        ),
        migrations.AddField(
            model_name="proposalnegotiation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("COUNTERED", "Countered"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="OPEN",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="proposalnegotiation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="proposalnegotiation",
            name="action",
            field=models.CharField(
                choices=[
                    ("COUNTER_OFFER", "Counter Offer"),
                    ("ACCEPT", "Accept"),
                    ("REJECT", "Reject"),
                    ("WITHDRAW", "Withdraw"),
                ],
                default="COUNTER_OFFER",
                max_length=30,
            ),
        ),
    ]
