# Generated by Django 5.2.11 on 2026-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_rename_scope_proposalnegotiation_proposed_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DEVELOPMENT_NEEDS", "Development Needs"),
                    ("DRAFT_DPR", "Draft DPR"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("UNDER_NEGOTIATION", "Under Negotiation"),
                    ("APPROVED", "Approved"),
                    ("SANCTIONED", "Sanctioned"),
                    ("FUNDS_RELEASED", "Funds Released"),
                    ("REJECTED", "Rejected"),
                    ("IN_EXECUTION", "In Execution"),
                ],
                default="DRAFT_DPR",
                max_length=50,
                verbose_name="Proposal Status",
            ),
        ),
    ]
