# Generated by Django 5.2.11 on 2026-08-17 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_alter_proposal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="release_status",
            field=models.CharField(
                choices=[
                    ("NOT_RELEASED", "Not Released"),
                    ("PARTIALLY_RELEASED", "Partially Released"),
                    ("FULLY_RELEASED", "Fully Released"),
                ],
                default="NOT_RELEASED",
                max_length=30,
                verbose_name="Fund Release Status",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="released_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                verbose_name="Cumulative Released Amount (INR)",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DEVELOPMENT_NEEDS", "Development Needs"),
                    ("DRAFT_DPR", "Draft DPR"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("UNDER_NEGOTIATION", "Under Negotiation"),
                    ("APPROVED", "Approved"),
                    ("SANCTIONED", "Sanctioned"),
                    ("PARTIALLY_RELEASED", "Partially Released"),
                    ("FUNDS_RELEASED", "Funds Released"),
                    ("REJECTED", "Rejected"),
                    ("IN_EXECUTION", "In Execution"),
                ],
                default="DRAFT_DPR",
                max_length=50,
                verbose_name="Proposal Status",
            ),
        ),
        migrations.CreateModel(
            name="ProposalFundRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("FULL", "One-Time Full Release"),
                            ("INSTALLMENT", "Installment-wise Release"),
                        ],
                        default="FULL",
                        max_length=20,
                        verbose_name="Release Type",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Installment Number"
                    ),
                ),
                (
                    "installment_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Installment Name / Tranche",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Released Amount (INR)",
                    ),
                ),
                (
                    "release_order_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Release Order Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description / Remarks"
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Released At"
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_releases",
                        to="myapp.proposal",
                        verbose_name="Proposal",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_proposal_funds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Released By",
                    ),
                ),
            ],
            options={
                "db_table": "txn_proposal_fund_release",
                "ordering": ["installment_number", "released_at"],
            },
        ),
    ]
