# Generated by Django 5.2.11 on 2026-08-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0032_proposal_release_status_proposal_released_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectexecution",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Work Assigned At"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="assigned_engineer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_engineer_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Engineer",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_officer_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Department Officer",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="assignment_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Work Assignment Notes"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="completion_verification_remarks",
            field=models.TextField(
                blank=True, null=True, verbose_name="Completion Verification Remarks"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="completion_verification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=30,
                null=True,
                verbose_name="Completion Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="completion_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completion Verified At"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="completion_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completion_verified_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Completion Verified By",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="officer_review_remarks",
            field=models.TextField(
                blank=True, null=True, verbose_name="Officer Review Remarks"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="officer_review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=30,
                null=True,
                verbose_name="Officer Review Status",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="officer_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Officer Reviewed At"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="officer_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="officer_reviewed_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Officer Reviewed By",
            ),
        ),
    ]
