# Generated by Django 5.2.11 on 2026-08-18 09:27

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0033_projectexecution_assigned_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExpenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Expenditure Amount (INR)",
                    ),
                ),
                (
                    "expenditure_date",
                    models.DateField(
                        default=myapp.models.get_today_date,
                        verbose_name="Expenditure Date",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("CIVIL_WORK", "Civil Work"),
                            ("ELECTRICAL_WORK", "Electrical Work"),
                            ("EQUIPMENT", "Equipment & Machinery"),
                            ("MATERIAL", "Material Supply"),
                            ("LABOUR", "Labour & Manpower"),
                            ("MISC", "Miscellaneous"),
                        ],
                        default="CIVIL_WORK",
                        max_length=50,
                        verbose_name="Expense Type",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Reference Order / Voucher Number",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, default="", verbose_name="Verification Remarks"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Recorded At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenditures",
                        to="myapp.projectexecution",
                        verbose_name="Project Execution",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_project_expenditures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By (Department Officer)",
                    ),
                ),
            ],
            options={
                "db_table": "prj_project_expenditure",
                "ordering": ["-created_at"],
            },
        ),
    ]
