# Generated by Django 5.2.11 on 2026-08-18 10:57

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_projectexpenditure"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectexecution",
            name="engineer_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Engineer Assigned At"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="field_assignment_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Field Engineer Assignment Notes"
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="officer_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Officer Assigned At"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="assignment_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Department Head Assignment Notes"
            ),
        ),
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
    ]
