# Generated by Django 5.2.11 on 2026-08-20 07:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_projectexecution_engineer_assigned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ambulance_code", models.CharField(max_length=50, unique=True)),
                (
                    "driver_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available / Operational"),
                            ("ON_CALL", "On Emergency Call"),
                            ("MAINTENANCE", "Under Maintenance"),
                        ],
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Point Geometry"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambulances",
                        to="myapp.facility",
                    ),
                ),
                (
                    "village_ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.villageward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambulance",
                "verbose_name_plural": "Ambulances",
                "db_table": "hlth_ambulance",
            },
        ),
        migrations.CreateModel(
            name="DiseaseRiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_name",
                    models.CharField(
                        max_length=150, verbose_name="Disease / Outbreak Name"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Cluster"),
                            ("HIGH", "High Outbreak"),
                            ("CRITICAL", "Critical Outbreak"),
                        ],
                        default="MEDIUM",
                        max_length=30,
                    ),
                ),
                ("affected_cases", models.PositiveIntegerField(default=1)),
                ("season", models.CharField(default="Monsoon 2026", max_length=50)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Point Geometry"
                    ),
                ),
                ("observed_at", models.DateField(default=myapp.models.get_today_date)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.block",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.district"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Risk Event",
                "verbose_name_plural": "Disease Risk Events",
                "db_table": "hlth_disease_risk_event",
            },
        ),
        migrations.CreateModel(
            name="FeedbackQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(default="HEALTHCARE_SERVICE", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Question Set",
                "verbose_name_plural": "Feedback Question Sets",
                "db_table": "fb_question_set",
            },
        ),
        migrations.CreateModel(
            name="FeedbackQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_CHOICE", "Single Choice Rating"),
                            ("RATING_5", "1 to 5 Star Rating"),
                            ("TEXT", "Text Note"),
                        ],
                        default="SINGLE_CHOICE",
                        max_length=30,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="Predefined option strings e.g. ['Very Good', 'Good', 'Average', 'Poor', 'Very Poor']",
                    ),
                ),
                (
                    "question_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="myapp.feedbackquestionset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Question",
                "verbose_name_plural": "Feedback Questions",
                "db_table": "fb_question",
            },
        ),
        migrations.CreateModel(
            name="FeedbackResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "citizen_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("response_value", models.CharField(max_length=255)),
                (
                    "sentiment_score",
                    models.FloatField(
                        default=3.0, help_text="1.0 (Very Poor) to 5.0 (Very Good)"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Point Geometry"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_responses",
                        to="myapp.facility",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="myapp.feedbackquestion",
                    ),
                ),
                (
                    "village_ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.villageward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Response",
                "verbose_name_plural": "Feedback Responses",
                "db_table": "fb_response",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GapModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(default="v1.0", max_length=30, unique=True),
                ),
                (
                    "weights",
                    models.JSONField(
                        default=dict, help_text="Component weights JSON (w1..w8)"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "approved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gap Model Version",
                "verbose_name_plural": "Gap Model Versions",
                "db_table": "ddss_gap_model_version",
            },
        ),
        migrations.CreateModel(
            name="GeotagVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_path", models.CharField(max_length=500)),
                ("exif_latitude", models.FloatField(blank=True, null=True)),
                ("exif_longitude", models.FloatField(blank=True, null=True)),
                ("submitted_latitude", models.FloatField(blank=True, null=True)),
                ("submitted_longitude", models.FloatField(blank=True, null=True)),
                ("distance_offset_meters", models.FloatField(blank=True, null=True)),
                ("inside_district", models.BooleanField(default=True)),
                ("is_duplicate_25m", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified (EXIF GPS & Boundary Matched)"),
                            (
                                "REVIEW",
                                "Review Required (Distance Offset or Border Warning)",
                            ),
                            (
                                "REJECTED",
                                "Rejected (No EXIF GPS / Out of Boundary / Far Distance)",
                            ),
                        ],
                        default="VERIFIED",
                        max_length=30,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Geotag Verification Log",
                "verbose_name_plural": "Geotag Verification Logs",
                "db_table": "gis_geotag_verification",
            },
        ),
        migrations.CreateModel(
            name="HealthFacilityIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        default="2026-Q3",
                        max_length=20,
                        verbose_name="Reporting Period",
                    ),
                ),
                (
                    "bed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total General Beds"
                    ),
                ),
                (
                    "icu_bed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ICU Beds Available"
                    ),
                ),
                (
                    "nicu_bed_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="NICU Beds Available"
                    ),
                ),
                (
                    "oxygen_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DEFICIT", "Deficit"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                (
                    "toilet_status",
                    models.CharField(
                        choices=[
                            ("ADEQUATE", "Adequate"),
                            ("INSUFFICIENT", "Insufficient"),
                            ("NONE", "None"),
                        ],
                        default="ADEQUATE",
                        max_length=30,
                    ),
                ),
                (
                    "ramp_status",
                    models.CharField(
                        choices=[
                            ("FUNCTIONAL", "Functional"),
                            ("NON_FUNCTIONAL", "Non-Functional"),
                            ("MISSING", "Missing"),
                        ],
                        default="FUNCTIONAL",
                        max_length=30,
                    ),
                ),
                (
                    "testing_equipment_status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("PARTIAL", "Partial Deficit"),
                            ("DEFICIT", "Major Deficit"),
                        ],
                        default="OPERATIONAL",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_indicators",
                        to="myapp.facility",
                        verbose_name="Facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Facility Indicator",
                "verbose_name_plural": "Health Facility Indicators",
                "db_table": "hlth_facility_indicator",
            },
        ),
        migrations.CreateModel(
            name="HealthStaffing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cadre",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Medical Officer / Doctor"),
                            ("NURSE", "Staff Nurse / ANM"),
                            ("LAB_TECH", "Lab Technician"),
                            ("ASHA", "ASHA Worker"),
                            ("ADMIN_STAFF", "Administrative Staff"),
                        ],
                        default="DOCTOR",
                        max_length=40,
                    ),
                ),
                ("sanctioned_count", models.PositiveIntegerField(default=0)),
                ("available_count", models.PositiveIntegerField(default=0)),
                ("vacancy_count", models.PositiveIntegerField(default=0)),
                ("as_of_date", models.DateField(default=myapp.models.get_today_date)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_records",
                        to="myapp.facility",
                        verbose_name="Facility",
                    ),
                ),
                (
                    "village_ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asha_staffing",
                        to="myapp.villageward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Staffing",
                "verbose_name_plural": "Health Staffing Records",
                "db_table": "hlth_staffing",
            },
        ),
        migrations.CreateModel(
            name="HealthWorkload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(default="2026-08", max_length=20)),
                (
                    "patient_visits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="OPD Patient Visits"
                    ),
                ),
                (
                    "admissions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="IPD Admissions"
                    ),
                ),
                (
                    "referrals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Patient Referrals Out"
                    ),
                ),
                (
                    "capacity_pressure",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("MODERATE", "Moderate Pressure"),
                            ("HIGH", "High Pressure"),
                            ("CRITICAL", "Critical Overload"),
                        ],
                        default="NORMAL",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_records",
                        to="myapp.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Workload",
                "verbose_name_plural": "Health Workload Records",
                "db_table": "hlth_workload",
            },
        ),
        migrations.CreateModel(
            name="MedicineStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(max_length=150, verbose_name="Medicine Name"),
                ),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical Emergency Medicine"),
                            ("ROUTINE", "Routine Essential Medicine"),
                            ("VACCINE", "Vaccine Cold-Chain"),
                        ],
                        default="ROUTINE",
                        max_length=30,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("minimum_quantity", models.PositiveIntegerField(default=100)),
                ("days_of_stock", models.PositiveIntegerField(default=30)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("ADEQUATE", "Adequate Stock"),
                            ("LOW", "Low Stock Warning"),
                            ("STOCKOUT", "Critical Stockout"),
                        ],
                        default="ADEQUATE",
                        max_length=30,
                    ),
                ),
                ("as_of", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_stocks",
                        to="myapp.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Stock",
                "verbose_name_plural": "Medicine Stock Records",
                "db_table": "hlth_medicine_stock",
            },
        ),
        migrations.CreateModel(
            name="PriorityLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Location / Need Title"
                    ),
                ),
                (
                    "gap_score",
                    models.FloatField(
                        default=0.0, verbose_name="Composite Gap Score (0-100)"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P1", "P1 / CRITICAL"),
                            ("P2", "P2 / HIGH"),
                            ("P3", "P3 / MEDIUM"),
                            ("P4", "P4 / LOW"),
                        ],
                        default="P2",
                        max_length=10,
                    ),
                ),
                (
                    "component_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown of demand, capacity, accessibility, HR, medicine, coverage, citizen feedback gaps",
                    ),
                ),
                (
                    "reason_codes",
                    models.JSONField(
                        default=list, help_text="Reason codes explaining score"
                    ),
                ),
                ("recommended_action", models.TextField(blank=True, null=True)),
                ("model_version", models.CharField(default="v1.0", max_length=30)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Point Geometry"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.block",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_locations",
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.district"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="priority_records",
                        to="myapp.facility",
                    ),
                ),
                (
                    "linked_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_priority_locations",
                        to="myapp.projectexecution",
                    ),
                ),
                (
                    "linked_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_priority_locations",
                        to="myapp.proposal",
                    ),
                ),
                (
                    "village_ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.villageward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Location",
                "verbose_name_plural": "Priority Locations",
                "db_table": "ddss_priority_location",
                "ordering": ["-gap_score"],
            },
        ),
        migrations.CreateModel(
            name="SpatialQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("query_json", models.JSONField(default=dict)),
                ("is_shared", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Spatial Query",
                "verbose_name_plural": "Spatial Queries",
                "db_table": "gis_spatial_query",
            },
        ),
        migrations.CreateModel(
            name="VaccinationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(default="2026-Q3", max_length=20)),
                ("target_population", models.PositiveIntegerField(default=1000)),
                ("vaccinated_count", models.PositiveIntegerField(default=850)),
                ("coverage_percent", models.FloatField(default=85.0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_metrics",
                        to="myapp.block",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccination Metric",
                "verbose_name_plural": "Vaccination Metrics",
                "db_table": "hlth_vaccination_metric",
            },
        ),
    ]
