# Generated by Django 5.2.11 on 2026-08-20 09:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0036_alter_projectexpenditure_expenditure_date_ambulance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Department Code",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="department",
            name="is_line_department",
            field=models.BooleanField(default=True, verbose_name="Is Line Department"),
        ),
        migrations.AddField(
            model_name="gapmodelversion",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gap_models",
                to="myapp.department",
            ),
        ),
        migrations.AlterField(
            model_name="gapmodelversion",
            name="version",
            field=models.CharField(default="v1.0", max_length=30),
        ),
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
        migrations.CreateModel(
            name="DepartmentIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Indicator Code (e.g. TEACHER_VACANCY, WATER_COVERAGE, ROAD_ACCESSIBILITY)",
                    ),
                ),
                (
                    "indicator_name",
                    models.CharField(max_length=200, verbose_name="Indicator Name"),
                ),
                ("value", models.FloatField(default=0.0, verbose_name="Numeric Value")),
                (
                    "unit",
                    models.CharField(
                        default="count",
                        max_length=50,
                        verbose_name="Unit of Measurement",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        default="2026-08",
                        max_length=30,
                        verbose_name="Reporting Period",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Line Department MIS",
                        max_length=200,
                        verbose_name="Data Source",
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Point Geometry"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Additional Metadata (JSONB)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_indicators",
                        to="myapp.block",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="myapp.department",
                        verbose_name="Line Department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_indicators",
                        to="myapp.district",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_indicators",
                        to="myapp.facility",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.state",
                    ),
                ),
                (
                    "village_ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.villageward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Indicator",
                "verbose_name_plural": "Department Indicators",
                "db_table": "ddss_department_indicator",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EducationFacilityIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(default="2026-08", max_length=20)),
                ("sanctioned_teachers", models.PositiveIntegerField(default=10)),
                ("available_teachers", models.PositiveIntegerField(default=7)),
                ("teacher_vacancies", models.PositiveIntegerField(default=3)),
                ("student_enrolment", models.PositiveIntegerField(default=320)),
                ("classroom_count", models.PositiveIntegerField(default=8)),
                ("drinking_water_status", models.BooleanField(default=True)),
                ("separate_girls_toilet", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_indicators",
                        to="myapp.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Facility Indicator",
                "verbose_name_plural": "Education Facility Indicators",
                "db_table": "edu_facility_indicator",
            },
        ),
        migrations.CreateModel(
            name="RoadIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "road_name",
                    models.CharField(
                        max_length=200, verbose_name="Road / Connectivity Name"
                    ),
                ),
                ("road_length_km", models.FloatField(default=12.5)),
                ("paved_length_km", models.FloatField(default=8.0)),
                ("unpaved_poor_length_km", models.FloatField(default=4.5)),
                (
                    "accessibility_status",
                    models.CharField(
                        choices=[
                            ("GOOD", "All-Weather Good Access"),
                            ("MODERATE", "Fair Access"),
                            ("POOR", "Poor Monsoon Accessibility"),
                        ],
                        default="POOR",
                        max_length=30,
                    ),
                ),
                ("bridge_gap_count", models.PositiveIntegerField(default=1)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Geometry Location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.block"
                    ),
                ),
            ],
            options={
                "verbose_name": "Road Indicator",
                "verbose_name_plural": "Road Indicators",
                "db_table": "pwd_road_indicator",
            },
        ),
        migrations.CreateModel(
            name="WaterFacilityIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(default="2026-08", max_length=20)),
                ("household_coverage_percent", models.FloatField(default=75.0)),
                (
                    "functional_tap_connections",
                    models.PositiveIntegerField(default=250),
                ),
                (
                    "non_functional_sources_count",
                    models.PositiveIntegerField(default=2),
                ),
                ("daily_supply_hours", models.FloatField(default=4.0)),
                (
                    "water_quality_status",
                    models.CharField(
                        choices=[
                            ("SAFE", "Safe Drinking Water"),
                            ("TURBID", "High Turbidity"),
                            ("CONTAMINATED", "Contaminated / Deficit"),
                        ],
                        default="SAFE",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="water_indicators",
                        to="myapp.facility",
                    ),
                ),
                (
                    "village_ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.villageward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Water Facility Indicator",
                "verbose_name_plural": "Water Facility Indicators",
                "db_table": "wtr_facility_indicator",
            },
        ),
    ]
