# Generated by Django 5.2.11 on 2026-08-20 09:38

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0037_department_code_department_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentindicator",
            name="data_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("VERIFIED", "Verified"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="VERIFIED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="departmentindicator",
            name="source_as_of",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data As Of Date"
            ),
        ),
        migrations.AddField(
            model_name="departmentindicator",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="departmentindicator",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_indicators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roadindicator",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.department",
            ),
        ),
        migrations.AddField(
            model_name="roadindicator",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.district",
            ),
        ),
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
    ]
