# Generated by Django 5.2.11 on 2026-09-01 12:09

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0038_departmentindicator_data_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
        migrations.CreateModel(
            name="FieldInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Inspection Title"),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Location / Entity Name",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        default="HEALTH", max_length=50, verbose_name="Department Code"
                    ),
                ),
                (
                    "inspector_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Assigned Inspector / Officer",
                    ),
                ),
                (
                    "inspector_designation",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Inspector Designation",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Scheduled Inspection Date"
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Scheduled Time"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Inspection Purpose / Checklist",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, null=True, verbose_name="Inspection Remarks / Notes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "coverage_gap_score",
                    models.FloatField(
                        default=0.0, verbose_name="Coverage Gap Score (%)"
                    ),
                ),
                ("priority_level", models.CharField(default="P1", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.block",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.district",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_inspections",
                        to="myapp.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Inspection",
                "verbose_name_plural": "Field Inspections",
                "db_table": "ddss_field_inspection",
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
    ]
