# Generated by Django 5.2.11 on 2026-09-01 12:42

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0039_alter_projectexpenditure_expenditure_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldinspection",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Field Inspection",
                "verbose_name_plural": "Field Inspections",
            },
        ),
        migrations.RemoveField(
            model_name="fieldinspection",
            name="purpose",
        ),
        migrations.AddField(
            model_name="fieldinspection",
            name="inspection_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Inspection ID (e.g. INS-2026-00101)",
            ),
        ),
        migrations.AddField(
            model_name="fieldinspection",
            name="inspection_purpose",
            field=models.TextField(
                blank=True, null=True, verbose_name="Inspection Purpose"
            ),
        ),
        migrations.AddField(
            model_name="fieldinspection",
            name="inspection_team",
            field=models.CharField(
                choices=[
                    ("Field Inspection Team", "Field Inspection Team"),
                    ("Technical Team", "Technical Team"),
                    ("Joint Inspection Team", "Joint Inspection Team"),
                ],
                default="Field Inspection Team",
                max_length=100,
                verbose_name="Inspection Team",
            ),
        ),
        migrations.AddField(
            model_name="fieldinspection",
            name="instructions",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Instructions / Notes for Field Team",
            ),
        ),
        migrations.AddField(
            model_name="fieldinspection",
            name="preferred_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Preferred Date"
            ),
        ),
        migrations.AlterField(
            model_name="fieldinspection",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("in_progress", "in_progress"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
    ]
