# Generated by Django 5.2.11 on 2026-09-02 04:58

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0040_alter_fieldinspection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldinspection",
            name="purpose",
            field=models.TextField(
                blank=True, null=True, verbose_name="Purpose / Checklist"
            ),
        ),
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
    ]
