# Generated by Django 5.2.11 on 2026-09-02 05:18

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0041_fieldinspection_purpose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldinspection",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("postponed", "postponed"),
                    ("in_progress", "in_progress"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
    ]
