# Generated by Django 5.2.11 on 2026-09-02 06:06

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0042_alter_fieldinspection_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldinspection",
            name="inspection_code",
        ),
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
    ]
