# Generated by Django 5.2.11 on 2026-09-02 07:37

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0043_remove_fieldinspection_inspection_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectexpenditure",
            name="expenditure_date",
            field=models.DateField(
                default=myapp.models.get_today_date, verbose_name="Expenditure Date"
            ),
        ),
        migrations.CreateModel(
            name="InterventionProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Proposal Title"),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Location / Entity Name",
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        default="Headquarters",
                        max_length=100,
                        verbose_name="Facility Type",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        default="HEALTH", max_length=50, verbose_name="Department Code"
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            (
                                "Infrastructure improvement",
                                "Infrastructure improvement",
                            ),
                            ("Additional staff", "Additional staff"),
                            ("Equipment", "Equipment"),
                            ("Repair / maintenance", "Repair / maintenance"),
                            ("New facility / expansion", "New facility / expansion"),
                            ("Service improvement", "Service improvement"),
                            (
                                "Connectivity / accessibility",
                                "Connectivity / accessibility",
                            ),
                            (
                                "Safety / hazard mitigation",
                                "Safety / hazard mitigation",
                            ),
                            ("Other", "Other"),
                        ],
                        default="Infrastructure improvement",
                        max_length=100,
                        verbose_name="Intervention Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Intervention Description / Need",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Estimated Cost (INR)",
                    ),
                ),
                (
                    "expected_timeline",
                    models.CharField(
                        default="30 days",
                        max_length=50,
                        verbose_name="Expected Timeline",
                    ),
                ),
                (
                    "coverage_gap_score",
                    models.FloatField(
                        default=0.0, verbose_name="Coverage Gap Score (%)"
                    ),
                ),
                ("priority_level", models.CharField(default="P1", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remarks / Authority Notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.block",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.department",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.district",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_proposals",
                        to="myapp.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention Proposal",
                "verbose_name_plural": "Intervention Proposals",
                "db_table": "ddss_intervention_proposal",
                "ordering": ["-created_at"],
            },
        ),
    ]
